import { Finding } from "./types";

export const MOCK_FINDINGS: Finding[] = [
  {
    finding_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    model_id: "urn:li:dataset:(urn:li:dataPlatform:dbt,b2fd91.order_entry_db.order_entry.customers,PROD)",
    model_name: "customers_risk_model",
    severity: "high",
    validated: true,
    evidence_scope: "org_wide",
    evidence_label: "Backed by company-wide pattern history",
    routed_to_team: "Payments Platform",
    severity_multiplier: 1.5,
    tag_source: "datahub_native",
    tag_source_label: "Verified DataHub Catalog Tag",
    status: "OPEN",
    actor: "J. Alvarez (Departed)",
    node_type: "threshold",
    event_timestamp: "2026-05-20T10:00:00Z",
    summary: "Undocumented threshold change by departing engineer J. Alvarez before departure",
    recommended_action: "Audit threshold logic and verify downstream customer categorization partitions",
    written_back: true,
    created_at: "2026-07-20T10:00:00Z",
  },
  {
    finding_id: "c3c4d5e6-f7a8-9012-bcde-f34567890123",
    model_id: "urn:li:dataset:(urn:li:dataPlatform:dbt,b2fd91.order_entry_db.order_entry.addresses,PROD)",
    model_name: "addresses_pipeline",
    severity: "high",
    validated: true,
    evidence_scope: "actor",
    evidence_label: "Backed by actor cross-model incident history",
    routed_to_team: "Logistics Engineering",
    severity_multiplier: 1.3,
    tag_source: "datahub_native",
    tag_source_label: "Verified DataHub Catalog Tag",
    status: "OPEN",
    actor: "J. Alvarez (Departed)",
    node_type: "pipeline_step",
    event_timestamp: "2026-04-10T09:00:00Z",
    summary: "Cross-model unreviewed transformation pipeline modification prior to departure window",
    recommended_action: "Repair addresses transformation pipeline and re-sync order_items records",
    written_back: false,
    created_at: "2026-07-18T14:30:00Z",
  },
  {
    finding_id: "e5f6a7b8-c9d0-1234-ef01-567890123456",
    model_id: "urn:li:dataset:(urn:li:dataPlatform:dbt,b2fd91.order_entry_db.order_entry.new_signup_scorer,PROD)",
    model_name: "new_signup_scorer",
    severity: "high",
    validated: false,
    evidence_scope: "industry_general",
    evidence_label: "Backed by published industry data (Cold-start fallback)",
    routed_to_team: "Onboarding Team",
    severity_multiplier: 1.0,
    tag_source: "inferred",
    tag_source_label: "Inferred from Schema",
    status: "OPEN",
    actor: "sarah.k@company.com",
    node_type: "feature",
    event_timestamp: "2026-07-15T08:20:00Z",
    summary: "Unreviewed feature addition on new cold-start model without historical incident log",
    recommended_action: "Collect first 14 days of post-deployment error rates for org validation",
    written_back: false,
    created_at: "2026-07-15T08:20:00Z",
  },
  {
    finding_id: "b2c3d4e5-f6a7-8901-bcde-f23456789012",
    model_id: "urn:li:dataset:(urn:li:dataPlatform:dbt,b2fd91.order_entry_db.order_entry.products,PROD)",
    model_name: "products_catalog_v2",
    severity: "medium",
    validated: false,
    evidence_scope: "org_wide",
    evidence_label: "Backed by company-wide pattern history",
    routed_to_team: "Catalog & Merchandising",
    severity_multiplier: 1.1,
    tag_source: "datahub_native",
    tag_source_label: "Verified DataHub Catalog Tag",
    status: "OPEN",
    actor: "R. Chen",
    node_type: "feature",
    event_timestamp: "2026-06-01T11:15:00Z",
    summary: "Undocumented column addition on products schema without backward compatibility check",
    recommended_action: "Verify dbt schema validity test assertions on products table",
    written_back: false,
    created_at: "2026-06-01T11:15:00Z",
  },
  {
    finding_id: "d4e5f6a7-b8c9-0123-def0-456789012345",
    model_id: "urn:li:dataset:(urn:li:dataPlatform:dbt,b2fd91.order_entry_db.order_entry.countries,PROD)",
    model_name: "countries_geo_filter",
    severity: "low",
    validated: false,
    evidence_scope: "industry_general",
    evidence_label: "Backed by published industry data (Cold-start fallback)",
    routed_to_team: "Global Expansion",
    severity_multiplier: 0.8,
    tag_source: "none",
    tag_source_label: "Untagged",
    status: "OPEN",
    actor: "M. Santos",
    node_type: "threshold",
    event_timestamp: "2026-07-01T15:30:00Z",
    summary: "Superficial threshold tweak with 0 historical incident precedents (Downgraded to Low)",
    recommended_action: "No immediate action required — scheduled for routine maintenance",
    written_back: false,
    created_at: "2026-07-01T15:30:00Z",
  },
];
